name: winget
on:
  release:
    types: [released]
  workflow_dispatch:
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          repository: jdx/winget-pkgs
          token: ${{ secrets.MISE_GH_TOKEN }}
          fetch-depth: 0
      - run: git config user.name mise-en-dev
      - run: git config user.email release@mise.jdx.dev
      - run: git remote add microsoft https://github.com/microsoft/winget-pkgs
      - run: git pull --rebase microsoft master
      - run: git push -f origin master
      - uses: vedantmgoyal9/winget-releaser@a8fff44b123f115ce4c21543edf8b677376fc7e0 # main
        with:
          identifier: jdx.mise
          max-versions-to-keep: 5
          token: ${{ secrets.MISE_GH_TOKEN }}
